title: "Federico Tropiano"
description: "PhD in Quantitative Finance â€“ Research, Teaching, Code"
baseurl: ""
url: "https://federicotropiano.github.io"

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one
